layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: ramonmac
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ramongtx
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Ruby
    web_url: https://www.ruby-lang.org/en/
    image_url: assets/img/ruby.png

  - name: Go
    web_url: https://golang.org
    image_url: assets/img/golang.png

  - name: GraphQL
    web_url: https://graphql.org/learn/
    image_url: assets/img/graphql.png

  - name: ReactJS
    web_url: https://icon-library.net/images/react-icon/react-icon-13.jpg
    image_url: assets/img/react.png

  - name: AWS
    web_url: https://aws.amazon.com
    image_url: assets/img/aws.png
